// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://coindistro.com/terms",
        "contact": {
            "name": "Coindistro Support",
            "url": "https://coindistro.com/support",
            "email": "support@coindistro.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/activity": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get security and activity history for the current user",
                "tags": [
                    "Security"
                ],
                "summary": "Get activity log",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.ActivityLogResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/change-password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change your current password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Security"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Current and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/forgot-password": {
            "post": {
                "description": "Send a password reset link to your email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "description": "Email address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.PasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login to your account",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Terminate the current session",
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Get a new access token using a refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register with referral code. Invite-only when enabled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new account",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/resend-verification": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Resend the email verification link",
                "tags": [
                    "Authentication"
                ],
                "summary": "Resend verification email",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Complete password reset with token and new password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Reset token and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.PasswordResetComplete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "get": {
                "description": "Verify email using the token sent to your email",
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify email address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all trusted devices for the current user",
                "tags": [
                    "Devices"
                ],
                "summary": "List trusted devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.DeviceResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/devices/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a trusted device by ID",
                "tags": [
                    "Devices"
                ],
                "summary": "Remove a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/admin/launchpool": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "Create launchpool campaign (admin)",
                "parameters": [
                    {
                        "description": "Campaign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.CreateLaunchpoolRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/admin/learn": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "Create learn \u0026 earn campaign (admin)",
                "parameters": [
                    {
                        "description": "Campaign",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.CreateLearnCampaignRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/admin/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "List all products including drafts (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "Create earn product (admin)",
                "parameters": [
                    {
                        "description": "Product",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/admin/products/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "Update earn product (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updates",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.UpdateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/admin/products/{id}/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "Product analytics (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.ProductAnalytics"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/earn/admin/products/{id}/participants": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "List product participants (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/admin/products/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn Admin"
                ],
                "summary": "Pause/resume/archive product (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "List earn transaction history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/launchpool": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "List launchpool campaigns",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/learn": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "List learn \u0026 earn campaigns",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/learn/{id}/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Record learning completion for reward eligibility",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Metadata",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.CompleteLearnRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/participations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "List user participations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/participations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Get participation details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Participation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/participations/{id}/add-funds": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Add funds to a participation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Participation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.AddFundsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/participations/{id}/exit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Exit a participation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Participation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reason",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.ExitParticipationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/participations/{id}/withdraw": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Withdraw from a participation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Participation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/portfolio": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Earn portfolio overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.PortfolioOverview"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/earn/products": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "List earn products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Featured only",
                        "name": "featured",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Supported asset",
                        "name": "asset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Per page",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/products/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Get earn product by ID or slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID or slug",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/products/{id}/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Join an earn product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Join request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.JoinProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/earn/referral/rewards": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "Referral reward summary and history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.ReferralRewardSummary"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/earn/rewards": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Earn"
                ],
                "summary": "List reward history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/invitations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all invitations sent by the current user",
                "tags": [
                    "Invitations"
                ],
                "summary": "List invitations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.InvitationResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Send an invitation email. Consumes one invitation credit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invitations"
                ],
                "summary": "Send invitation",
                "parameters": [
                    {
                        "description": "Invitation details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.SendInvitationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.InvitationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/referrals/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get referral code, stats, and tree",
                "tags": [
                    "Referrals"
                ],
                "summary": "Get referral dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.ReferralDashboardResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all active sessions for the current user",
                "tags": [
                    "Sessions"
                ],
                "summary": "List active sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.SessionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sessions/terminate-all": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Terminate all sessions except the current one",
                "tags": [
                    "Sessions"
                ],
                "summary": "Terminate all sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Terminate a specific session by ID",
                "tags": [
                    "Sessions"
                ],
                "summary": "Terminate a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/check-email": {
            "get": {
                "description": "Check if an email is already registered",
                "tags": [
                    "Users"
                ],
                "summary": "Check email availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email to check",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/check-username": {
            "get": {
                "description": "Check if a username is already taken",
                "tags": [
                    "Users"
                ],
                "summary": "Check username availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username to check",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile",
                "tags": [
                    "Users"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update profile fields like display_name, username, country, timezone",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update current user profile",
                "parameters": [
                    {
                        "description": "Profile fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_coindistro_backend_internal_earn_models.AddFundsRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.CompleteLearnRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "description": "Optional metadata from Academy client",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.CreateLaunchpoolRequest": {
            "type": "object",
            "required": [
                "name",
                "supported_assets",
                "window_end",
                "window_start"
            ],
            "properties": {
                "allocation_rules": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "reward_distribution": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "type": "string"
                },
                "supported_assets": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "window_end": {
                    "type": "string"
                },
                "window_start": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.CreateLearnCampaignRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "academy_course_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "reward_amount": {
                    "type": "number"
                },
                "reward_asset": {
                    "type": "string"
                },
                "starts_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.CreateProductRequest": {
            "type": "object",
            "required": [
                "category",
                "name",
                "slug",
                "supported_assets"
            ],
            "properties": {
                "capacity_total": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration_days": {
                    "type": "integer"
                },
                "eligibility": {
                    "type": "object",
                    "additionalProperties": true
                },
                "ends_at": {
                    "type": "string"
                },
                "featured": {
                    "type": "boolean"
                },
                "max_allocation": {
                    "type": "number"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "min_allocation": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "reward_apr": {
                    "type": "number"
                },
                "reward_model": {
                    "type": "string"
                },
                "risk_level": {
                    "type": "string"
                },
                "rules": {
                    "type": "object",
                    "additionalProperties": true
                },
                "slug": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "starts_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "strategy_profiles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "supported_assets": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.ExitParticipationRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.JoinProductRequest": {
            "type": "object",
            "required": [
                "amount",
                "asset"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "strategy_profile": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.PortfolioOverview": {
            "type": "object",
            "properties": {
                "active_products": {
                    "type": "integer"
                },
                "allocation_by_asset": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "allocation_by_product": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "available_balance": {
                    "description": "future wallet",
                    "type": "number"
                },
                "estimated_rewards": {
                    "type": "number"
                },
                "lifetime_rewards": {
                    "type": "number"
                },
                "locked_balance": {
                    "type": "number"
                },
                "todays_rewards": {
                    "type": "number"
                },
                "total_assets_in_earn": {
                    "type": "number"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.ProductAnalytics": {
            "type": "object",
            "properties": {
                "avg_allocation": {
                    "type": "number"
                },
                "capacity_total": {
                    "type": "number"
                },
                "capacity_used": {
                    "type": "number"
                },
                "capacity_used_pct": {
                    "type": "number"
                },
                "participants": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "total_allocated": {
                    "type": "number"
                },
                "total_rewards": {
                    "type": "number"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.ReferralMilestone": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "required_referrals": {
                    "type": "integer"
                },
                "reward_amount": {
                    "type": "number"
                },
                "reward_asset": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.ReferralRewardClaim": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "asset": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "granted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "milestone_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.ReferralRewardSummary": {
            "type": "object",
            "properties": {
                "claims": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.ReferralRewardClaim"
                    }
                },
                "milestones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_coindistro_backend_internal_earn_models.ReferralMilestone"
                    }
                },
                "total_eligible": {
                    "type": "number"
                },
                "total_granted": {
                    "type": "number"
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.UpdateProductRequest": {
            "type": "object",
            "properties": {
                "capacity_total": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "duration_days": {
                    "type": "integer"
                },
                "eligibility": {
                    "type": "object",
                    "additionalProperties": true
                },
                "ends_at": {
                    "type": "string"
                },
                "featured": {
                    "type": "boolean"
                },
                "max_allocation": {
                    "type": "number"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "min_allocation": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "reward_apr": {
                    "type": "number"
                },
                "reward_model": {
                    "type": "string"
                },
                "risk_level": {
                    "type": "string"
                },
                "rules": {
                    "type": "object",
                    "additionalProperties": true
                },
                "starts_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "strategy_profiles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "supported_assets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_coindistro_backend_internal_earn_models.WithdrawRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.ActivityLogResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "device_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.UserResponse"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.DeviceResponse": {
            "type": "object",
            "properties": {
                "browser": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "first_seen_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_current": {
                    "type": "boolean"
                },
                "is_trusted": {
                    "type": "boolean"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operating_system": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.InvitationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "consumed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "invitee_email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.PasswordResetComplete": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.PasswordResetRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.ReferralDashboardResponse": {
            "type": "object",
            "properties": {
                "conversion_rate": {
                    "type": "number"
                },
                "invitation_credits": {
                    "type": "integer"
                },
                "leaderboard_rank": {
                    "type": "integer"
                },
                "pending_invites": {
                    "type": "integer"
                },
                "referral_code": {
                    "type": "string"
                },
                "referral_link": {
                    "type": "string"
                },
                "referral_tree": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.ReferralNode"
                    }
                },
                "rewards_earned": {
                    "type": "number"
                },
                "successful_invites": {
                    "type": "integer"
                },
                "total_invites": {
                    "type": "integer"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.ReferralNode": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_coindistro_backend_internal_identity_models.ReferralNode"
                    }
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "referral_code"
            ],
            "properties": {
                "country": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "referral_code": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.SendInvitationRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "maxLength": 500
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.SessionResponse": {
            "type": "object",
            "properties": {
                "browser": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_current": {
                    "type": "boolean"
                },
                "last_activity_at": {
                    "type": "string"
                },
                "login_at": {
                    "type": "string"
                },
                "operating_system": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 100
                },
                "timezone": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "github_com_coindistro_backend_internal_identity_models.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "genesis_number": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_founder": {
                    "type": "boolean"
                },
                "is_genesis": {
                    "type": "boolean"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "last_login_at": {
                    "type": "string"
                },
                "referral_code": {
                    "type": "string"
                },
                "referred_by": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_response.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_coindistro_backend_internal_response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.APIError"
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_coindistro_backend_internal_response.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_coindistro_backend_internal_response.Meta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "Enter the token with the ` + "`" + `Bearer ` + "`" + ` prefix, e.g. \"Bearer abcde12345\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "coindistro.onrender.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https"},
	Title:            "Coindistro API",
	Description:      "Coindistro — One Platform. Everything Crypto. API backend for Africa's next-generation crypto financial ecosystem.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
